frisboo:
  corebanking:
    saga:
      outbox:
        enabled: true
        dbTableName: customer_transactions.outbox
      inbox:
        enabled: true
        dbTableName: customer_transactions.inbox

spring:
  main:
    banner-mode: off

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    display-request-duration: true
    disable-swagger-default-url: true
