spring:
  application.name: customer-service (DEV)

  exposed:
    show-sql: true
    generate-ddl: false

  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/customers?rewriteBatchedInserts=true
    execute-in-transaction: true
    locations: classpath:db/migration/postgres
    placeholders:
      outbox_table_name: customer_transactions.outbox
      inbox_table_name: customer_transactions.inbox

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: DEBUG
    com.frisboo.corebanking.customerservice: ERROR
    org.springframework.web: ERROR
    org.springframework.web.reactive: DEBUG
    org.springframework.context: DEBUG
    org.hibernate: ERROR
    io.r2dbc.postgresql.PARAM: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
