[versions]
corebanking-convention = "0.0.1-alpha-2"
corebanking-frisboo = "0.0.1-alpha1"
corebanking-grpccontracts-idempotencyservice = "0.0.1-alpha1"
corebanking-grpccontracts-sagaservice = "0.0.1-alpha1"

[libraries]
corebanking-frisboo-bom = { group = "com.frisboo.corebanking", name = "frisboo-bom", version.ref = "corebanking-frisboo" }
corebanking-frisboo-core = { group = "com.frisboo.corebanking", name = "frisboo-core" }
corebanking-frisboo-data = { group = "com.frisboo.corebanking", name = "frisboo-data" }
corebanking-frisboo-grpc = { group = "com.frisboo.corebanking", name = "frisboo-grpc" }
corebanking-frisboo-http = { group = "com.frisboo.corebanking", name = "frisboo-http" }
corebanking-frisboo-persistence = { group = "com.frisboo.corebanking", name = "frisboo-persistence" }
corebanking-frisboo-tests = { group = "com.frisboo.corebanking", name = "frisboo-tests" }
corebanking-grpccontracts-idempotencyservice = { group = "com.frisboo.corebanking.grpccontracts", name = "idempotencyservice", version.ref = "corebanking-grpccontracts-idempotencyservice" }
corebanking-grpccontracts-sagaservice = { group = "com.frisboo.corebanking.grpccontracts", name = "sagaservice", version.ref = "corebanking-grpccontracts-sagaservice" }

[plugins]
coreBankingConvention = { id = "com.frisboo.corebanking.gradle-convention-plugin", version.ref = "corebanking-convention" }
